node {
    stage 'Checkout'
    checkout scm

    stage 'Build'

    stage 'Deploy'

    marathon(
        url: 'http://leader.mesos:8080',
        filename: 'dev/digest/marathon.json'
    )

    marathon(
        url: 'http://leader.mesos:8080',
        filename: 'dev/ingest/marathon.json'
    )

    marathon(
        url: 'http://leader.mesos:8080',
        filename: 'dev/ui/marathon.json'
    )
}
