node {
    stage 'Checkout'
    checkout scm

    stage 'Build'
    sh "echo Building ..."

    stage 'Deploy'
    marathon(
        url: 'http://leader.mesos:8080',
        filename: 'prod/ingest/marathon.json'
    )

    marathon(
        url: 'http://leader.mesos:8080',
        filename: 'prod/ui/marathon.json'
    )
}
